<?php
$this->headLink()->appendStylesheet($this->basePath() . '/common/admin/css/login.min.css');
$this->headScript()->appendFile($this->basePath() . '/common/admin/js/login.min.js');
?>

<div class="span4 offset4">
	<div id="login-panel" class="block">
		<div class="block-header block-header-inverse">
			<h2><?php echo $this->translate('Dang nhap')?></h2>
		</div>
		<div class="block-body">
			<form id="login-form" class="form-horizontal" method="post"
				action="admin-login.php">
				<div class="errors">
					<div class="alert alert-danger" data-bind="visible: error">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
						<strong><?php echo $this->translate('Loi!')?></strong> <span
							data-bind="text: error_message"></span>
					</div>
					<div class="alert alert-success" data-bind="visible: success">
                                <?php echo $this->translate('Dang nhap thanh cong. Dang chuyen huong...')?>
                            </div>
				</div>
				<div class="control-group">
					<label for="email-input" class="control-label"><?php echo $this->translate('Email')?></label>

					<div class="controls">
						<input id="email-input" type="email" name="email"
							data-bind="value: email" required>
					</div>
				</div>
				<div class="control-group">
					<label for="password-input" class="control-label"><?php echo $this->translate('Mat khau')?></label>

					<div class="controls">
						<input id="password-input" type="password" name="password"
							data-bind="value: password" required>
					</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary"
						data-bind="click: login, text: login_text"><?php echo $this->translate('Dang nhap')?></button>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
var loginViewModel = new kendo.observable({
    email: "",
    password: "",
    success: false,
    error: false,
    error_message: "",
    login_text: "<?php echo $this->translate('Dang nhap')?>",
    login: function () {
        var self = this;
        self.set("login_text", "<?php echo $this->translate('Dang dang nhap')?>");
        // Send
        jQuery.post("<?php echo $this->url('administrator/authentication/authenticate')?>", {
            email: this.email,
            password: this.password
            <?php if ($this->redirectUrl) : ?>
            ,redirect_url: <?php echo urlencode($this->redirectUrl)?>
            <?php endif; ?>
        }, function (response) {
            if (!response.success) {
                // if error
                self.set("success", false);
                self.set("error", true);
                self.set("error_message", response.errorMessage);
                self.set("login_text", "<?php echo $this->translate('Dang nhap')?>");
            } else {
                self.set("error", false);
                self.set("success", true);
                // Redirect to control panel
                window.location.href = response.redirectUrl;
            }

            self.set("email", "");
            self.set("password", "");
        });
        return false;
    }
});

kendo.bind($('#login-form'), loginViewModel);
</script>