<?php
$this->headLink()->appendStylesheet($this->basePath() . '/common/css/404.min.css');
$this->headScript()->prependFile($this->basePath() . '/nivo-slider/js/jquery.nivo.slider.pack.js');
?>

<div class="span12">
	<h1><?php echo $this->translate(':( 404')?></h1>

	<h2>
	   <?php echo $this->translate('Duong dan ban truy cap khong ton tai hoac da bi xoa <br> Hay kiem tra lai duong dan hoac truy cap vao trang khac.')?>
	</h2>
</div>