<?php
$this->headLink()->prependStylesheet($this->basePath() . '/common/css/post.min.css');

$this->headScript()->prependFile($this->basePath() . '/common/js/post.min.js');

$post = $this->post;

// Excerpt
$postContentParts = explode("<div style=\"page-break-after: always;\"><span style=\"display:none\">&nbsp;</span></div>", $post['content']);
$postExcerpt = $postContentParts[0];

// Post thumbnail
$postImageUrls = array();
$thumbnail = 'http://blx.vn/common/images/logo-square-75x75.jpg';
preg_match_all('#<img.+src="(?<image_url>(.+)\.(jpg|png))"#imsU', $post['content'], $postImageUrls);
if (isset($postImageUrls['image_url'][0]) && $postImageUrls['image_url'][0] != '#') {
    $thumbnail = $postImageUrls[0];
}

$this->headTitle()->prepend(strip_tags(html_entity_decode($post['title'])));
$this->headMeta()
    ->setName('description', $postExcerpt)
    ->setName('title', $post['title'])
    ->setName('image_src', $thumbnail);
?>

<div class="span3 sidebar">
	<ul class="nav nav-list sidenav">
		<li class="nav-header"><?php echo $this->translate('Chuyen muc')?></li>
		<?php foreach ($this->categories as $category) : ?>
		    <?php if ($post['category_id'] == $category['category_id']) : ?>
    	    <li class="active">
    	    <?php else : ?>
    	    
		
		
		
		
		
		
		
		
	<li>
    	    <?php endif; ?>
		    <a
			href="<?php echo $this->url('news/category', array('category_slug' => $category['slug']))?>"><?php echo $category['title']?></a>
		</li>
		<?php endforeach; ?>
	</ul>
</div>

<div class="span9 news-container">
	<!-- Post Detail --><div class="row news-item">
				<div class="span9">
			<div class="block news-block block-square">
				<div class="block-header">
					<h2>
						<a
									href="<?php echo $this->url('news/detail', array('category_slug' => $post['category']['slug'], 'post_slug' => $post['slug'], 'post_id' => $post['post_id']))?>"
									title="<?php echo $post['title'] ?>"><?php echo $post['title'] ?></a>
					</h2>
				</div>
				<div class="block-body">
					<div class="news-content">
						<div class="author">
							<span>
                                <?php echo $this->translate('dang boi')?>
                                <span class="authorName"><?php echo $post['author']['full_name'] ?></span>&nbsp;<?php echo $this->translate('vao luc')?>&nbsp;<?php echo $post['last_updated']->format('H:i:s') ?>&nbsp;<?php echo $this->translate('ngay')?>&nbsp;<?php echo $post['last_updated']->format('d/m/Y')?>
							</span>
						</div>
						<div class="newsText">
							<?php echo $post['content']?>
						</div>
					</div>
				</div>
				<div class="block-footer">
					<div id="fb-root"></div>
					<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '1408214906061696',                   // App ID from the app dashboard
      channelUrl : '//blx.vn/fbchannel.html',            // Channel file for x-domain comms
      status     : true,                                 // Check Facebook Login status
      xfbml      : true                                  // Look for social plugins on the page
    });

    // Additional initialization code such as adding Event Listeners goes here
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     js.async = true;
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
					<div class="fb-like"
								data-href="http://blx.vn<?php echo $this->url('news/detail', array('category_slug' => $post['category']['slug'], 'post_slug' => $post['slug'], 'post_id' => $post['post_id']))?>"
								data-width="600" data-show-faces="true" data-send="true"></div>
				</div>
			</div>
		</div>
	</div>

	<!-- Comments -->
	<div class="row comments">
		<div class="span9">
			<div class="block block-square comment-block">
				<!-- Facebook comment -->
				<div class="fb-comments"
							data-href="http://blx.vn<?php echo $this->url('news/detail', array('category_slug' => $post['category']['slug'], 'post_slug' => $post['slug'], 'post_id' => $post['post_id']))?>"
							data-width="670"></div>
			</div>
		</div>
	</div>

		
		</div>