<?php
$this->headMeta()->setName('description', $this->translate('news_index_meta_description'));
$this->headLink()->prependStylesheet($this->basePath() . '/common/css/post.min.css');

$this->headScript()->prependFile($this->basePath() . '/common/js/post.min.js');

if ($this->categoryQuery) {
    $this->headMeta()->setName('description', $this->categoryQuery['title'] . ' | ' . $this->translate('news_index_meta_description'));
    $this->headTitle()->prepend($this->categoryQuery['title']);
} else {
    $this->headTitle()->prepend($this->translate('Tin tuc'));
}

?>

<div class="span3 sidebar">
	<ul class="nav nav-list sidenav">
		<li class="nav-header"><?php echo $this->translate('Chuyen muc')?></li>
		<?php foreach ($this->categories as $category) : ?>
		<?php if ($this->categoryQuery && $this->categoryQuery['category_id'] == $category['category_id']) : ?>
		  <li class="active">
		  <?php else : ?>
		<li>
		<?php endif; ?>
		<a
			href="<?php echo $this->url('news/category', array('category_slug' => $category['slug']))?>"><?php echo $category['title']?></a>
		</li>
		<?php endforeach; ?>
	</ul>
</div>

<div class="span9 news-container">
    <?php foreach ($this->posts as $post) : ?>
    <?php
        // Data Initialize
        $author = $this->userModel->cache->getUser(array(
            'user_id' => $post['author_id']
        ));
        if ($author)
            $post->author = $author;
            
            // Category
        $category = $this->categoryModel->cache->getCategory(array(
            'category_id' => $post['category_id']
        ));
        if ($category) {
            $post->category = $category;
        }
        
        // Datetime
        $post->last_updated = new \DateTime($post['last_updated']);
        
        // Post Slug
        $post->slug = $this->stringUtilityCache->seoUrl($post['title']);
        
        // Only show excerpt
        $postContentParts = explode("<div style=\"page-break-after: always;\"><span style=\"display:none\">&nbsp;</span></div>", $post->content);
        $postExcerpt = $postContentParts[0];
        
        ?>
	<div class="row news-item">
		<div class="span9">
			<div class="block news-block block-square">
				<div class="block-header">
					<h2>
						<a
							href="<?php echo $this->url('news/detail', array('category_slug' => $post['category']['slug'], 'post_slug' => $post['slug'], 'post_id' => $post['post_id']))?>"
							title="<?php echo $post['title'] ?>"><?php echo $post['title'] ?></a>
					</h2>
				</div>
				<div class="block-body">
					<div class="news-content">
						<div class="author">
							<span>
                                <?php echo $this->translate('dang boi')?>
                                <a href="#" class="authorName"><?php echo $post['author']['full_name'] ?></a>
                                &nbsp;<?php echo $this->translate('vao luc')?>&nbsp;
                                <?php echo $post['last_updated']->format('H:i:s') ?>&nbsp;<?php echo $this->translate('ngay')?>&nbsp;<?php echo $post['last_updated']->format('d/m/Y')?>
							</span>
						</div>
						<div class="newsText">
							<?php 
							//echo $post['content']
							echo $postExcerpt;
							?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	
	<!-- Pagination -->
	<div class="row">
		<div class="span9">
			<div class="block pagination-block block-square">
                <?php
                if ($this->categoryQuery) {
                    $route = 'news/category/paginator';
                    $categorySlug = $this->categoryQuery['slug'];
                } else {
                    $route = 'news/paginator';
                    $categorySlug = null;
                }
                echo $this->paginationControl($this->posts, 'Sliding', 'partial/paginator', array(
                    'route' => $route,
                    'category_slug' => $categorySlug
                ));
                ?>
			</div>
		</div>
	</div>
</div>