<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Module.php',
    'Application\Controller\DocumentController' => __DIR__ . '/src/Application/Controller/DocumentController.php',
    'Application\Controller\FixtureController'  => __DIR__ . '/src/Application/Controller/FixtureController.php',
    'Application\Controller\GuidingController'  => __DIR__ . '/src/Application/Controller/GuidingController.php',
    'Application\Controller\IndexController'    => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\PostController'     => __DIR__ . '/src/Application/Controller/PostController.php',
    'Application\Controller\ResultController'   => __DIR__ . '/src/Application/Controller/ResultController.php',
    'Application\Paginator\Post\DbAdapter'      => __DIR__ . '/src/Application/Paginator/Post/DbAdapter.php',
    'Application\View\Helper\Breadcrum'         => __DIR__ . '/src/Application/View/Helper/Breadcrumb.php',
);
