<?php
$this->headLink()->prependStylesheet($this->basePath() . '/common/css/document.min.css');
$this->headScript()
    ->prependFile($this->basePath() . '/common/js/document.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.binder.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.data.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.core.min.js');

$this->headtitle()->prepend($this->translate('Tai lieu on tap thi bang lai xe hang A1/A2'));

?>

<div class="span12 page-title">
	<h1><?php echo $this->translate('Tai lieu on tap thi bang lai xe hang A1/A2')?></h1>
</div>

<div class="span3 docs-sidebar">
	<ul class="nav nav-list docs-sidenav">
		<li><a href="#road-sign"><i class="road-sign-icon base64"></i><i
				class="icon-chevron-right"></i>&nbsp;<?php echo $this->translate('Bien bao giao thong')?></a></li>
		<li><a href="#theoretical-question"><i
				class="theoretical-question-icon base64"></i><i
				class="icon-chevron-right"></i>&nbsp;<?php echo $this->translate('Cau hoi ly thuyet')?></a></li>
	</ul>
</div>

<div class="span9">
	<section id="road-sign" class="block">
		<div class="block-header">
			<h2>
				<i class="road-sign-icon base64"></i><?php echo $this->translate('Bien bao giao thong su dung trong de thi bang lai xe hang A1')?>
			</h2>
		</div>
		<div class="block-body" data-template="signGroupTemplate" data-bind="source: signGroups">
            <div class="loading">
                <img src="<?php echo $this->basePath() ?>/common/images/ajax-loader.gif">
                <span><?php echo $this->translate('Dang tai bien bao')?></span>
            </div>
		</div>
	</section>

    <script id="signGroupTemplate" type="text/x-kendo-template">
        <div>
            <h3>
                <span data-bind="text: groupSignTitle"></span>
                <span class="description" data-bind="text: groupSignDescription"></span>
            </h3>
            <ul class="signboard-command" data-template="signTemplate" data-bind="source: signs"></ul>
        </div>
    </script>

    <script id="signTemplate" type="text/x-kendo-template">
        <li>
            <a href="\#" class="" data-toggle="popover" data-content="" data-bind="attr: {data-content: description, data-original-title: signTitle}">
                <img data-bind="attr: {src: imgSrc}">
                <span data-bind="text: signCode"></span>
            </a>
        </li>
    </script>

	<section id="theoretical-question">
		<div class="block">
			<div class="block-header">
				<h2>
					<i class="theoretical-question-icon base64"></i><?php echo $this->translate('Bai on tap ly thuyet sat hach, cap giay phep lai xe hang A1, A2')?>
				</h2>
			</div>
			<div class="block-body">
				<div class="notice">
					<strong><?php echo $this->translate('Chu y:')?></strong>
					<ul>
						<li><em><?php echo $this->translate('Trong De Thi chinh thuc ban lam 1 de 20 cau hoi trong thoi gian 15 phut va dat tu 16-20 cau dung la Do.')?></em></li>
						<li><em><?php echo $this->translate('Trong Bo Tai lieu de de hoc chung toi tam thoi chia ra moi de khoang 16 - 17 cau.')?></em></li>
						<li><em><?php echo $this->translate('Ban hoc het bo de co nghia da lam tat ca 150 cau hoi thi sat hach A1.')?></em></li>
						<li><em><?php echo $this->translate('Trong cau tra loi nhieu truong hop ban phai chon ca 2 y dung. Luc do ban se tich vao 2 y. Vd: y 1 va 3 -> tich vao 1, tich vao 3')?></em></li>
					</ul>
				</div>
				<ul class="nav nav-tabs" id="threadTabs">
					<li class="active"><a href="#thread-1"><?php echo $this->translate('De')?>&nbsp;1</a></li>
					<li><a href="#thread-2"><?php echo $this->translate('De')?>&nbsp;2</a></li>
					<li><a href="#thread-3"><?php echo $this->translate('De')?>&nbsp;3</a></li>
					<li><a href="#thread-4"><?php echo $this->translate('De')?>&nbsp;4</a></li>
					<li><a href="#thread-5"><?php echo $this->translate('De')?>&nbsp;5</a></li>
					<li><a href="#thread-6"><?php echo $this->translate('De')?>&nbsp;6</a></li>
					<li><a href="#thread-7"><?php echo $this->translate('De')?>&nbsp;7</a></li>
					<li><a href="#thread-8"><?php echo $this->translate('De')?>&nbsp;8</a></li>
					<li><a href="#thread-9"><?php echo $this->translate('De')?>&nbsp;9</a></li>
					<li><a href="#thread-10"><?php echo $this->translate('De')?>&nbsp;10</a></li>
				</ul>

				<div class="tab-content">
					<div class="tab-pane active thread" id="thread-1">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so')?><span>&nbsp;1</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix"><?php echo $this->translate('Duong bo gom:')?></p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_1_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_1_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_1_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
							<table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>2</td>
										<td>2</td>
										<td>1</td>
										<td>2</td>
										<td>4</td>
										<td>3</td>
										<td>4</td>
										<td>3</td>
										<td>4</td>
										<td>3</td>
										<td>4</td>
										<td>2</td>
										<td>2</td>
										<td>2</td>
										<td>4</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-2">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>2</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_2_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_3_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_4_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_5_3')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_5_4')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_6_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_8_2')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-3">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>3</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_6_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-4">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>4</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_1_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_3_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_7_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_7_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-5">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>5</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_2_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_3_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_5_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-6">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>6</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-7">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>7</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_5_3')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_5_4')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_8_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
											<li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
											<li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-8">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>8</span>
							</div>
						</div>

						<div class="thread-body">
                            <ul class="questions">
                                <li class="question"><label><?php echo $this->translate('Cau 1')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_1')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_1_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_1_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 2')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_2')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_2_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_2_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 3')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_3')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_3_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_3_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 4')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_4')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_4_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_4_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_4_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 5')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_5')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_5_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_5_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 6')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_6')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 7')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_7')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_7_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_7_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_8')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_8_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_8_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <p class="answer-prefix">
                                            <img
                                                src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
                                                alt="">
                                        </p>
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
                                            <li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
                                            <li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
                                            <li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
                                        </ol>
                                    </div></li>
                            </ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-9">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>9</span>
							</div>
						</div>

						<div class="thread-body">
                            <ul class="questions">
                                <li class="question"><label><?php echo $this->translate('Cau 1')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_1')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_1_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_1_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_1_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 2')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_2')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_2_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_2_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_2_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 3')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_3')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_3_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_3_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_3_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 4')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_4')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 5')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_5')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_5_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_5_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_5_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 6')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_6')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_6_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_6_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_6_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 7')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_7')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_8')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_8_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_8_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_8_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <p class="answer-prefix">
                                            <img
                                                src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
                                                alt="">
                                        </p>
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
                                            <li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
                                            <li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
                                            <li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
                                        </ol>
                                    </div></li>
                            </ul>
						</div>

						<div class="thread-footer"></div>
					</div>
					<div class="tab-pane thread" id="thread-10">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>10</span>
							</div>
						</div>

						<div class="thread-body">
                            <ul class="questions">
                                <li class="question"><label><?php echo $this->translate('Cau 1')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_1')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 2')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_2')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_2_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_2_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_2_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 3')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_3')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 4')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_4')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_4_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_4_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 5')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_5')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_5_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_5_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_5_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 6')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_6')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 7')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_7')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_8')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_8_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_8_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question picture-question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('Thu tu cac xe di nhu the nao la dung quy tac giao thong&#63;')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <p class="answer-prefix">
                                            <img
                                                src="<?php echo $this->basePath()?>/common/images/question-13-image-296x162.png"
                                                alt="">
                                        </p>
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('Xe tai, xe lam, xe con, mo to.')?></li>
                                            <li class="answer"><?php echo $this->translate('Xe tai, mo to, xe lam, xe con.')?></li>
                                            <li class="answer"><?php echo $this->translate('Xe lam, xe tai, xe con, mo to.')?></li>
                                            <li class="answer"><?php echo $this->translate('Mo to, xe lam, xe tai, xe con.')?></li>
                                        </ol>
                                    </div></li>
                            </ul>
						</div>

						<div class="thread-footer"></div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>