<?php
$this->headMeta()->appendName('description', $this->translate('document_meta_description'));
$this->headLink()->prependStylesheet($this->basePath() . '/common/css/document.min.css');
$this->headScript()
    ->prependFile($this->basePath() . '/common/js/document.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.binder.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.data.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.core.min.js');

$this->headtitle()->prepend($this->translate('Tai lieu on tap thi bang lai xe hang A1/A2'));

?>

<div class="span12 page-title">
	<h1><?php echo $this->translate('Tai lieu on tap thi bang lai xe hang A1/A2')?></h1>
</div>

<div class="span3 docs-sidebar">
	<ul class="nav nav-list docs-sidenav">
		<li><a href="#road-sign"><i class="road-sign-icon base64"></i><i
				class="icon-chevron-right"></i>&nbsp;<?php echo $this->translate('Bien bao giao thong')?></a></li>
		<li><a href="#theoretical-question"><i
				class="theoretical-question-icon base64"></i><i
				class="icon-chevron-right"></i>&nbsp;<?php echo $this->translate('Cau hoi ly thuyet')?></a></li>
	</ul>
</div>

<div class="span9">
	<section id="road-sign" class="block">
		<div class="block-header">
			<h2>
				<i class="road-sign-icon base64"></i><?php echo $this->translate('Bien bao giao thong su dung trong de thi bang lai xe hang A1')?>
			</h2>
		</div>
		<div class="block-body" data-template="signGroupTemplate" data-bind="source: signGroups">
            <div class="loading">
                <img src="<?php echo $this->basePath() ?>/common/images/ajax-loader.gif">
                <span><?php echo $this->translate('Dang tai bien bao')?></span>
            </div>
		</div>
	</section>

    <script id="signGroupTemplate" type="text/x-kendo-template">
        <div>
            <h3>
                <span data-bind="text: groupSignTitle"></span>
                <span class="description" data-bind="text: groupSignDescription"></span>
            </h3>
            <ul class="signboard-command" data-template="signTemplate" data-bind="source: signs"></ul>
        </div>
    </script>

    <script id="signTemplate" type="text/x-kendo-template">
        <li>
            <a href="\#" class="" data-toggle="popover" data-content="" data-bind="attr: {data-content: description, data-original-title: signTitle}">
                <img data-bind="attr: {src: imgSrc}">
                <span data-bind="text: signCode"></span>
            </a>
        </li>
    </script>

	<section id="theoretical-question">
		<div class="block">
			<div class="block-header">
				<h2>
					<i class="theoretical-question-icon base64"></i><?php echo $this->translate('Bai on tap ly thuyet sat hach, cap giay phep lai xe hang A1, A2')?>
				</h2>
			</div>
			<div class="block-body">
				<div class="notice">
					<strong><?php echo $this->translate('Chu y:')?></strong>
					<ul>
						<li><em><?php echo $this->translate('Trong De Thi chinh thuc ban lam 1 de 20 cau hoi trong thoi gian 15 phut va dat tu 16-20 cau dung la Do.')?></em></li>
						<li><em><?php echo $this->translate('Trong Bo Tai lieu de de hoc chung toi tam thoi chia ra moi de khoang 16 - 17 cau.')?></em></li>
						<li><em><?php echo $this->translate('Ban hoc het bo de co nghia da lam tat ca 150 cau hoi thi sat hach A1.')?></em></li>
						<li><em><?php echo $this->translate('Trong cau tra loi nhieu truong hop ban phai chon ca 2 y dung. Luc do ban se tich vao 2 y. Vd: y 1 va 3 -> tich vao 1, tich vao 3')?></em></li>
					</ul>
				</div>
				<ul class="nav nav-tabs" id="threadTabs">
					<li class="active"><a href="#thread-1"><?php echo $this->translate('De')?>&nbsp;1</a></li>
					<li><a href="#thread-2"><?php echo $this->translate('De')?>&nbsp;2</a></li>
					<li><a href="#thread-3"><?php echo $this->translate('De')?>&nbsp;3</a></li>
					<li><a href="#thread-4"><?php echo $this->translate('De')?>&nbsp;4</a></li>
					<li><a href="#thread-5"><?php echo $this->translate('De')?>&nbsp;5</a></li>
					<li><a href="#thread-6"><?php echo $this->translate('De')?>&nbsp;6</a></li>
					<li><a href="#thread-7"><?php echo $this->translate('De')?>&nbsp;7</a></li>
					<li><a href="#thread-8"><?php echo $this->translate('De')?>&nbsp;8</a></li>
					<li><a href="#thread-9"><?php echo $this->translate('De')?>&nbsp;9</a></li>
					<li><a href="#thread-10"><?php echo $this->translate('De')?>&nbsp;10</a></li>
				</ul>

				<div class="tab-content">
					<div class="tab-pane active thread" id="thread-1">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so')?><span>&nbsp;1</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix"><?php echo $this->translate('Duong bo gom:')?></p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_1_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_1_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_1_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_1_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_9_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_9_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_10_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_10_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_11_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_11_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_12_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_13_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_13_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_14_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_14_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_15_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 16')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_1_16')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_1_16.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_1_16_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_16_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_1_16_3')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
							<table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
										<td>16</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>1-2</td> <!-- 1 -->
										<td>1</td> <!-- 2 -->
										<td>1</td> <!-- 3 -->
										<td>2</td> <!-- 4 -->
										<td>1</td> <!-- 5 -->
										<td>1</td> <!-- 6 -->
										<td>1-2</td> <!-- 7 -->
										<td>2</td> <!-- 8 -->
										<td>3</td> <!-- 9 -->
										<td>2</td> <!-- 10 -->
										<td>3</td> <!-- 11 -->
										<td>1</td> <!-- 12 -->
										<td>2</td> <!-- 13 -->
										<td>3</td> <!-- 14 -->
										<td>2</td> <!-- 15 -->
										<td>1</td> <!-- 16 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-2">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>2</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_2_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_3_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_4_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_5_3')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_5_4')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_6_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_2_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_2_8_2')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_9_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_9_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_10_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_10_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_12_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_12_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_13_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_14_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_15_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 16')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_2_16')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_2_16.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_2_16_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_16_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_2_16_3')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
										<td>16</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>1</td> <!-- 1 -->
										<td>2</td> <!-- 2 -->
										<td>1-2</td> <!-- 3 -->
										<td>1-2</td> <!-- 4 -->
										<td>2-3</td> <!-- 5 -->
										<td>1-2</td> <!-- 6 -->
										<td>1-2</td> <!-- 7 -->
										<td>1</td> <!-- 8 -->
										<td>1</td> <!-- 9 -->
										<td>3</td> <!-- 10 -->
										<td>1</td> <!-- 11 -->
										<td>2</td> <!-- 12 -->
										<td>2</td> <!-- 13 -->
										<td>1</td> <!-- 14 -->
										<td>3</td> <!-- 15 -->
										<td>1</td> <!-- 16 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-3">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>3</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_6_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_3_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_3_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_9_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_9_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_10_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_10_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_12_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_12_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_13_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_13_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_14_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_14_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_3_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_3_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_3_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_3_15_3')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>2</td> <!-- 1 -->
										<td>1</td> <!-- 2 -->
										<td>1</td> <!-- 3 -->
										<td>2</td> <!-- 4 -->
										<td>1</td> <!-- 5 -->
										<td>1-2</td> <!-- 6 -->
										<td>1-2</td> <!-- 7 -->
										<td>3</td> <!-- 8 -->
										<td>3</td> <!-- 9 -->
										<td>4</td> <!-- 10 -->
										<td>2</td> <!-- 11 -->
										<td>1</td> <!-- 12 -->
										<td>3</td> <!-- 13 -->
										<td>1</td> <!-- 14 -->
										<td>2</td> <!-- 15 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-4">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>4</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_1_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_3_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_7_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_7_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_4_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_4_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_9_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_9_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_10_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_12_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_12_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_13_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_14_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_14_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_15_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_15_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 16')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_4_16')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_4_16.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_4_16_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_4_16_2')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
										<td>16</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>1-2</td> <!-- 1 -->
										<td>3</td> <!-- 2 -->
										<td>1-2</td> <!-- 3 -->
										<td>3</td> <!-- 4 -->
										<td>2-3</td> <!-- 5 -->
										<td>2</td> <!-- 6 -->
										<td>1-2</td> <!-- 7 -->
										<td>2</td> <!-- 8 -->
										<td>2</td> <!-- 9 -->
										<td>1</td> <!-- 10 -->
										<td>2</td> <!-- 11 -->
										<td>2</td> <!-- 12 -->
										<td>1</td> <!-- 13 -->
										<td>1</td> <!-- 14 -->
										<td>3</td> <!-- 15 -->
										<td>2</td> <!-- 16 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-5">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>5</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_2_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_3_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_5_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_5_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_5_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_9_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_10_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_12_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_12_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_13_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_14_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_14_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_15_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 16')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_5_16')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_5_16.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_5_16_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_16_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_16_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_5_16_4')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
										<td>16</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>1</td> <!-- 1 -->
										<td>1-2</td> <!-- 2 -->
										<td>1</td> <!-- 3 -->
										<td>2</td> <!-- 4 -->
										<td>2</td> <!-- 5 -->
										<td>1</td> <!-- 6 -->
										<td>2</td> <!-- 7 -->
										<td>2</td> <!-- 8 -->
										<td>1</td> <!-- 9 -->
										<td>2</td> <!-- 10 -->
										<td>1-2</td> <!-- 11 -->
										<td>3</td> <!-- 12 -->
										<td>2</td> <!-- 13 -->
										<td>4</td> <!-- 14 -->
										<td>1</td> <!-- 15 -->
										<td>3</td> <!-- 16 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-6">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>6</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_5_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_6_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_6_8_3')?></li>
										</ol>
									</div></li>
								<li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_9_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_10_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_11_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_11_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_12_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_13_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_14_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_14_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_15_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 16')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_6_16')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_6_16.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_6_16_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_16_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_16_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_6_16_4')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
										<td>16</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>2</td> <!-- 1 -->
										<td>3</td> <!-- 2 -->
										<td>1-2</td> <!-- 3 -->
										<td>1</td> <!-- 4 -->
										<td>2-3</td> <!-- 5 -->
										<td>1-2</td> <!-- 6 -->
										<td>2</td> <!-- 7 -->
										<td>3</td> <!-- 8 -->
										<td>1</td> <!-- 9 -->
										<td>1</td> <!-- 10 -->
										<td>3</td> <!-- 11 -->
										<td>2</td> <!-- 12 -->
										<td>3</td> <!-- 13 -->
										<td>3</td> <!-- 14 -->
										<td>2</td> <!-- 15 -->
										<td>13</td> <!-- 16 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-7">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>7</span>
							</div>
						</div>

						<div class="thread-body">
							<ul class="questions">
								<li class="question"><label><?php echo $this->translate('Cau 1')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_1')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_1_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_1_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_1_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 2')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_2')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_2_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_2_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_2_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 3')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_3')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_3_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_3_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_3_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 4')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_4')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_4_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_4_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_4_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 5')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_5')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_5_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_5_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_5_3')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_5_4')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 6')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_6')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_6_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_6_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_6_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 7')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_7')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_7_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_7_2')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 8')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_8')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_8_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_8_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_8_3')?></li>
										</ol>
									</div></li>
								<li class="question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dap_an_7_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_9_3')?></li>
											<li class="answer"><?php echo $this->translate('dap_an_7_9_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_7_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_7_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_10_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_7_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_7_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_7_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_7_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_12_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_7_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_7_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_13_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_7_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_7_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_14_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_14_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_7_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_7_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_7_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_15_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_7_15_4')?></li>
										</ol>
									</div></li>
							</ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>3</td> <!-- 1 -->
										<td>3</td> <!-- 2 -->
										<td>1</td> <!-- 3 -->
										<td>3</td> <!-- 4 -->
										<td>1</td> <!-- 5 -->
										<td>1-3</td> <!-- 6 -->
										<td>1</td> <!-- 7 -->
										<td>3</td> <!-- 8 -->
										<td>3</td> <!-- 9 -->
										<td>2</td> <!-- 10 -->
										<td>2</td> <!-- 11 -->
										<td>1</td> <!-- 12 -->
										<td>2</td> <!-- 13 -->
										<td>1</td> <!-- 14 -->
										<td>3</td> <!-- 15 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-8">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>8</span>
							</div>
						</div>

						<div class="thread-body">
                            <ul class="questions">
                                <li class="question"><label><?php echo $this->translate('Cau 1')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_1')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_1_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_1_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_1_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 2')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_2')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_2_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_2_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 3')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_3')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_3_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_3_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 4')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_4')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_4_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_4_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_4_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 5')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_5')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_5_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_5_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 6')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_6')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_6_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 7')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_7')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_7_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_7_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_7_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_8_8')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_8_8_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_8_8_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_9_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_10_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_12_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_13_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_13_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_14_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_8_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_8_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_8_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_8_15_3')?></li>
										</ol>
									</div></li>
                            </ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>1</td> <!-- 1 -->
										<td>1</td> <!-- 2 -->
										<td>1-2</td> <!-- 3 -->
										<td>1-2</td> <!-- 4 -->
										<td>1</td> <!-- 5 -->
										<td>2</td> <!-- 6 -->
										<td>1-2</td> <!-- 7 -->
										<td>1-2</td> <!-- 8 -->
										<td>2</td> <!-- 9 -->
										<td>1</td> <!-- 10 -->
										<td>2</td> <!-- 11 -->
										<td>1</td> <!-- 12 -->
										<td>2</td> <!-- 13 -->
										<td>3</td> <!-- 14 -->
										<td>2</td> <!-- 15 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-9">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>9</span>
							</div>
						</div>

						<div class="thread-body">
                            <ul class="questions">
                                <li class="question"><label><?php echo $this->translate('Cau 1')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_1')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_1_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_1_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_1_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 2')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_2')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_2_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_2_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_2_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 3')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_3')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_3_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_3_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_3_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 4')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_4')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_4_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 5')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_5')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_5_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_5_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_5_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 6')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_6')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_6_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_6_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_6_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 7')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_7')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_7_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_9_8')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_9_8_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_8_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_9_8_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_9_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_9_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_9_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_10_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_10_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_11_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_11_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_12_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_12_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_13_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_14_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_14_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_9_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_9_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_9_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_15_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_9_15_4')?></li>
										</ol>
									</div></li>
                            </ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>3</td> <!-- 1 -->
										<td>2</td> <!-- 2 -->
										<td>2-3</td> <!-- 3 -->
										<td>2</td> <!-- 4 -->
										<td>1</td> <!-- 5 -->
										<td>1</td> <!-- 6 -->
										<td>1-2</td> <!-- 7 -->
										<td>2</td> <!-- 8 -->
										<td>2</td> <!-- 9 -->
										<td>1</td> <!-- 10 -->
										<td>3</td> <!-- 11 -->
										<td>3</td> <!-- 12 -->
										<td>2</td> <!-- 13 -->
										<td>3</td> <!-- 14 -->
										<td>2</td> <!-- 15 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="tab-pane thread" id="thread-10">
						<div class="thread-header">
							<h3>
								<span class="mark-1"><?php echo $this->translate('Bai on tap ly thuyet')?></span>
								<br> <span class="mark-2"><?php echo $this->translate('sat hach, cap giay phep lai xe')?></span>
								<br> <span class="mark-3"><?php echo $this->translate('Hang <strong>A1, A2</strong>')?></span>
							</h3>

							<div class="thread-number">
								<?php echo $this->translate('Bai so&nbsp;')?><span>10</span>
							</div>
						</div>

						<div class="thread-body">
                            <ul class="questions">
                                <li class="question"><label><?php echo $this->translate('Cau 1')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_1')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_1_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 2')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_2')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_2_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_2_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_2_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 3')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_3')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_3_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 4')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_4')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_4_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_4_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 5')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_5')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_5_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_5_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_5_3')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 6')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_6')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_6_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 7')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_7')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_2')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_3')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_7_4')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question"><label><?php echo $this->translate('Cau 8')?></label>

                                    <p class="question-p"><?php echo $this->translate('cau_hoi_10_8')?></p>

                                    <div class="clearfix"></div>
                                    <div class="question-body">
                                        <ol class="answers">
                                            <li class="answer"><?php echo $this->translate('dap_an_10_8_1')?></li>
                                            <li class="answer"><?php echo $this->translate('dap_an_10_8_2')?></li>
                                        </ol>
                                    </div></li>
                                <li class="question picture-question"><label><?php echo $this->translate('Cau 9')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_9')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_9.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_9_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_9_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 10')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_10')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_10.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_10_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_10_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_10_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 11')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_11')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_11.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_11_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_11_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_11_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 12')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_12')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_12.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_12_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_12_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_12_3')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_12_4')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 13')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_13')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_13.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_13_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_13_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_13_3')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 14')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_14')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_14.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_14_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_14_2')?></li>
										</ol>
									</div></li>
									<li class="question picture-question"><label><?php echo $this->translate('Cau 15')?></label>

									<p class="question-p"><?php echo $this->translate('cau_hoi_10_15')?></p>

									<div class="clearfix"></div>
									<div class="question-body">
										<p class="answer-prefix">
											<img
												src="<?php echo $this->basePath()?>/common/images/cau_hoi_10_15.jpg"
												alt="">
										</p>
										<ol class="answers">
											<li class="answer"><?php echo $this->translate('dan_an_10_15_1')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_15_2')?></li>
											<li class="answer"><?php echo $this->translate('dan_an_10_15_3')?></li>
										</ol>
									</div></li>
                            </ul>
						</div>

						<div class="thread-footer">
						  <table class="table table-bordered">
								<thead>
									<tr>
										<th colspan="16"><?php echo $this->translate('Dap an')?></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><?php echo $this->translate('Cau')?></td>
										<td>1</td>
										<td>2</td>
										<td>3</td>
										<td>4</td>
										<td>5</td>
										<td>6</td>
										<td>7</td>
										<td>8</td>
										<td>9</td>
										<td>10</td>
										<td>11</td>
										<td>12</td>
										<td>13</td>
										<td>14</td>
										<td>15</td>
									</tr>
									<tr class="result">
										<td><?php echo $this->translate('Dap an')?></td>
										<td>3</td> <!-- 1 -->
										<td>1</td> <!-- 2 -->
										<td>3</td> <!-- 3 -->
										<td>1-2</td> <!-- 4 -->
										<td>2</td> <!-- 5 -->
										<td>2-3</td> <!-- 6 -->
										<td>1-3</td> <!-- 7 -->
										<td>1-2</td> <!-- 8 -->
										<td>2</td> <!-- 9 -->
										<td>2</td> <!-- 10 -->
										<td>2</td> <!-- 11 -->
										<td>2</td> <!-- 12 -->
										<td>3</td> <!-- 13 -->
										<td>2</td> <!-- 14 -->
										<td>1-2</td> <!-- 15 -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>