<?php echo $this->doctype(); ?>
<html lang="vi">
<head>
    <?php echo $this->headTitle($this->translate('BLX Admin control panel'))->setSeparator(' - ')->setAutoEscape(false)?>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Styles -->
<?php

$this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/common/images/favicon.ico'
))
    ->prependStylesheet($this->basePath() . '/common/admin/css/common.min.css')
    ->prependStylesheet($this->basePath() . '/kendoui/styles/kendo.dataviz.bootstrap.min.css')
    ->prependStylesheet($this->basePath() . '/common/admin/css/kendo.min.css')
    ->prependStylesheet($this->basePath() . '/common/admin/css/kendo.common.min.css')
    ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css');

echo $this->headlink();

$this->headScript()
    ->prependFile($this->basePath() . '/common/admin/js/common.min.js')
    ->prependFile($this->basePath() . '/kendoui/js/kendo.web.min.js')
    ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/jquery/js/jquery-1.10.2.min.js');

echo $this->headScript();

if ($this->currentUser) {
	$currentUserInfo = $this->currentUser->getInfo();
?>

</head>
<body id="<?php echo str_replace('\\', '', $this->controllerClass) ?>">

	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand"><?php echo $this->translate('BLX.VN')?></a>

				<div class="nav-collapse collapse navbar-responsive-collapse">
					<ul class="nav">
						<li><a href="<?php echo $this->url('administrator') ?>"><?php echo $this->translate('Trang chu')?></a>
						</li>
						<?php if ($this->currentUser->isAllowed('profile','management') && $this->currentUser->isAllowed('profile','read')) : ?>
						<li><a href="<?php echo $this->url('administrator/profiles') ?>"><?php echo $this->translate('Ho so')?></a></li>
						<?php endif;?>
						<?php if ($this->currentUser->isAllowed('venue','management') && $this->currentUser->isAllowed('venue','read')) : ?>
						<li><a href="<?php echo $this->url('administrator/venues') ?>"><?php echo $this->translate('Dia diem thi')?></a></li>
						<?php endif;?>
						<?php if ($this->currentUser->isAllowed('post_category','management') || $this->currentUser->isAllowed('post','management')) : ?>
						<li class="dropdown"><a
							href="<?php echo $this->url('administrator/posts') ?>"
							class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Tin tuc')?>&nbsp;<b
								class="caret"></b></a>
							<ul class="dropdown-menu">
							    <?php if ($this->currentUser->isAllowed('post_category','management') && $this->currentUser->isAllowed('post_category','read')) : ?>
								<li><a
									href="<?php echo $this->url('administrator/categories') ?>"><?php echo $this->translate('Chuyen muc')?></a></li>
								<?php endif; ?>
								<?php if ($this->currentUser->isAllowed('post','management') && $this->currentUser->isAllowed('post','read')) : ?>
								<li><a href="<?php echo $this->url('administrator/posts') ?>"><?php echo $this->translate('Bai viet')?></a></li>
								<?php endif; ?>
							</ul></li>
					    <?php endif;?>
					    <?php if ($this->currentUser->isAllowed('user','management') || $this->currentUser->isAllowed('permission','management')) : ?>
						<li class="dropdown"><a
							href="<?php echo $this->url('administrator/users') ?>"
							class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Thanh vien')?>&nbsp;<b
								class="caret"></b></a>
							<ul class="dropdown-menu">
							    <?php if ($this->currentUser->isAllowed('user','management') && $this->currentUser->isAllowed('user','read')) : ?>
								<li><a href="<?php echo $this->url('administrator/users') ?>"><?php echo $this->translate('Thanh vien')?></a></li>
								<?php endif; ?>
								<?php if($this->currentUser->isAllowed('permission','read')) : ?>
								<li><a href="<?php echo $this->url('administrator/permissions') ?>"><?php echo $this->translate('Phan quyen')?></a></li>
								<?php endif; ?>
							</ul></li>
					    <?php endif;?>
						<?php if ($this->currentUser->isAllowed('setting','read')) : ?>
						<li><a href="<?php echo $this->url('administrator/system') ?>"><?php echo $this->translate('He thong')?></a></li>
						<?php endif; ?>
					</ul>

					<ul class="nav pull-right">
						<li class="divider-vertical"></li>
						<li class="dropdown"><a
							href="<?php echo $this->url('administrator/users') ?>"
							class="dropdown-toggle" data-toggle="dropdown"><?php echo $currentUserInfo['full_name'] ?>&nbsp;<b
								class="caret"></b></a>
							<ul class="dropdown-menu">
								<!-- <li><a href="<?php echo $this->url('administrator/users') ?>"><?php echo $this->translate('Thong tin ca nhan')?></a></li>
								<li class="divider"></li> -->
								<li><a
									href="<?php echo $this->url('administrator/authentication/logout') ?>"><?php echo $this->translate('Dang xuat')?></a></li>
							</ul></li>
					</ul>

					<?php if ($this->controllerClass == 'Administrator\\Controller\\ProfileController' && $this->currentUser->isAllowed('profile', 'quick_search')) :?>
					<form id="quickSearch" class="navbar-search pull-right" action="">
						<label> <input type="text" class="search-query span3"
							placeholder="<?php echo $this->translate('Tim nhanh bang ten hoac so dien thoai')?>"
							name="q">
						</label>
					</form>
					<?php endif;?>
				</div>
			</div>
		</div>
	</div>

	<!-- Quick search results -->
	<div id="quick-search-result" class="container hide">
		<div class="row"></div>
	</div>
	
	<?php echo $this->content?>

</body>
</html>
<?php } ?>