<?php echo $this->doctype(); ?>
<html lang="vi">
<head>
    <?php echo $this->headTitle($this->translate('BLX.VN - Thi bang lai xe may hang A1/A2 tai Ha Noi'))->setSeparator(' | ')->setAutoEscape(false)?>
    <?php
    
    $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
    
    echo $this->headMeta();
    ?>
    
    <!-- Styles -->
    <?php
    
    $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/common/images/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/common/css/common.min.css')
        ->prependStylesheet($this->basePath() . '/nivo-slider/css/nivo-slider.min.css')
        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css');
    
    echo $this->headlink();
    ?>
    
    <script type="text/javascript">
        var baseUrl = "<?php echo $this->url('home')?>";
    </script>

</head>
<body id="home-page">
	<div id="header" class="container">
		<div id="main-nav" class="navbar">
			<div class="navbar-inner">
				<ul class="nav">
					<li><a class="logo" href="<?php echo $this->url('home') ?>"> <img
							src="<?php echo $this->basePath()?>/common/images/logo-blx-49x28.png"
							width="49"
							height="28"
							alt="<?php echo $this->translate('BLX.VN - Thi bang lai xe may hang A1/A2 tai Ha Noi')?>"
							title="<?php echo $this->translate('BLX.VN - Thi bang lai xe may hang A1/A2 tai Ha Noi')?>">
					</a></li>
					<li><a href="<?php echo $this->url('fixture')?>"><?php echo $this->translate('Lich thi')?></a></li>
					<li><a href="<?php echo $this->url('result')?>"><?php echo $this->translate('Ket qua thi')?></a></li>
					<li><a href="<?php echo $this->url('document')?>"><?php echo $this->translate('Tai lieu on thi')?></a></li>
					<li><a href="<?php echo $this->url('guiding')?>"><?php echo $this->translate('Huong dan thi')?></a></li>
					<li><a href="<?php echo $this->url('news')?>"><?php echo $this->translate('Tin tuc')?></a></li>
				</ul>
			</div>
		</div>
	</div>

	<div id="content" class="container">
		<div class="row">

<?php echo $this->content?>

<div id="breadcrumb" class="span12">
				<div class="block">
					<div class="block-header">
					    <?php if (isset($this->breadcrumb)) : ?>
						<ul>
						    <?php foreach ($this->breadcrumb as $key => $item) : ?>
    							<li
								class="<?php echo isset($item['class']) ? $item['class'] : '' ?>">
    							     <?php if ($key < count($this->breadcrumb)-1) : ?>
    								 <a href="<?php echo isset($item['url'])?$item['url']:'' ?>"><?php echo isset($item['content']) ? $item['content'] : ''?></a>
    						         <?php else : ?>
    						         <a><?php echo isset($item['content']) ? $item['content'] : ''?></a>
    						         <?php endif; ?>
    						    </li>
    							<?php if ($key < count($this->breadcrumb)-1) : ?>
    							<li class="separator"></li>
    							<?php endif;?>
							<?php endforeach; ?>
						</ul>
						<?php endif; ?>
					</div>

					<div class="block-body">
						<ul class="link-group-list">
							<li>
								<ul>
									<li class="link-group-title"><span><?php echo $this->translate('BLX.VN')?></span>
									</li>
									<li class="link"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Trang chu')?></a>
									</li>
									<li class="link"><a
										href="<?php echo $this->url('news/category', array('category_slug' => 'dieu-khoan-dieu-le'))?>"><?php echo $this->translate('Dieu khoan')?></a>
									</li>
								</ul>
							</li>
							<li>
								<ul>
									<li class="link-group-title"><span><?php echo $this->translate('Thi bang lai xe')?></span>
									</li>
									<li class="link"><a
										href="<?php echo $this->url('home')?>#nop-ho-so"><?php echo $this->translate('Nop ho so')?></a>
									</li>
									<li class="link"><a href="<?php echo $this->url('fixture')?>"><?php echo $this->translate('Xem lich thi')?></a>
									</li>
									<li class="link"><a href="<?php echo $this->url('guiding')?>"><?php echo $this->translate('Huong dan thi')?></a>
									</li>
									<li class="link"><a href="<?php echo $this->url('result')?>"><?php echo $this->translate('Ket qua thi')?></a>
									</li>
								</ul>
							</li>
							<li>
								<ul>
									<li class="link-group-title"><span><?php echo $this->translate('Cong tac vien')?></span>
									</li>
									<li class="link"><a href="#"><?php echo $this->translate('Dang ky')?></a>
									</li>
									<li class="link"><a href="#"><?php echo $this->translate('Dieu le')?></a>
									</li>
								</ul>
							</li>
							<li>
								<ul>
									<li class="link-group-title"><span><?php echo $this->translate('Tro giup')?></span>
									</li>
									<li class="link"><a
										href="<?php echo $this->url('news/category', array('category_slug' => 'hoi-dap'))?>"><?php echo $this->translate('Cau hoi thuong gap')?></a>
									</li>
								</ul>
							</li>
						</ul>

						<div class="interesting">
							<h3><?php echo $this->translate('Thu vi')?></h3>

							<div class="interesting-thing">
								<img class="interesting-thumb"
									src="<?php echo $this->basePath()?>/common/images/interesting.png" width="94" height="59"
									alt="" title="">

								<p class="interesting-description">
                        <?php echo $this->translate('noi_dung_thu_vi')?>
                    </p>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>

	<div id="footer" class="container">
		<div class="row">
			<div class="span6">
				<p id="copyright"><?php echo $this->translate('copyright')?></p>
			</div>

			<div class="span4 offset2">
				<p id="designer">
                <?php echo $this->translate('Thiet ke va xay dung boi Luu Hoang Nam')?>
            </p>
			</div>

			<div class="span12">
				<div id="back-link">
					<ul>
						<li><a href="#"><?php echo $this->translate('Bang lai xe')?></a></li>
						<li><a href="#"><?php echo $this->translate('Thi bang lai xe')?></a></li>
						<li><a href="#"><?php echo $this->translate('Bang lai xe o Ha Noi')?></a>
						</li>
						<li><a href="#"><?php echo $this->translate('Bang lai xe A1')?></a></li>
						<li><a href="#"><?php echo $this->translate('Thi bang lai xe may')?></a>
						</li>
						<li><a href="#"><?php echo $this->translate('Thi bang lai xe moto')?></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div id="blx-social-network-fixed-left-side">
		<ul>
			<li class="facebook"><a href="https://www.facebook.com/blxvn"> <i></i>
			</a></li>
			<li class="youtube"><a
				href="https://www.youtube.com/channel/UCPxfXvNhC0VtfxEIEHkIzmA"> <i></i>
			</a></li>
			<li class="twitter"><a href="https://twitter.com/blxvn"> <i></i>
			</a></li>
			<li class="google-plus"><a
				href="https://plus.google.com/110647196881609058917/posts"> <i></i>
			</a></li>
		</ul>
	</div>

<?php
$this->headScript()
// ->prependFile($this->basePath() . '/common/js/common.min.js')
            ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')->prependFile($this->basePath() . '/jquery/js/jquery-1.10.2.min.js');
    
    echo $this->headScript();
    ?>

<script type="text/javascript">
$(document).ready(function(){$("#blx-social-network-fixed-left-side").css("left",($(window).width()-960)/2-50);});
</script>

	<script async="async">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42985392-1', 'blx.vn');
    ga('send', 'pageview');

</script>

</body>
</html>