<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Administrator\Module'                              => __DIR__ . '/Module.php',
    'Administrator\Controller\AuthenticationController' => __DIR__ . '/src/Administrator/Controller/AuthenticationController.php',
    'Administrator\Controller\CategoryController'       => __DIR__ . '/src/Administrator/Controller/CategoryController.php',
    'Administrator\Controller\CollaboratorController'   => __DIR__ . '/src/Administrator/Controller/CollaboratorController.php',
    'Administrator\Controller\IndexController'          => __DIR__ . '/src/Administrator/Controller/IndexController.php',
    'Administrator\Controller\PostController'           => __DIR__ . '/src/Administrator/Controller/PostController.php',
    'Administrator\Controller\ProfileController'        => __DIR__ . '/src/Administrator/Controller/ProfileController.php',
    'Administrator\Controller\SystemController'         => __DIR__ . '/src/Administrator/Controller/SystemController.php',
    'Administrator\Controller\UserController'           => __DIR__ . '/src/Administrator/Controller/UserController.php',
    'Administrator\Controller\UserGroupController'      => __DIR__ . '/src/Administrator/Controller/UserGroupController.php',
    'Administrator\Controller\VenueController'          => __DIR__ . '/src/Administrator/Controller/VenueController.php',
    'Administrator\Model\Category'                      => __DIR__ . '/src/Administrator/Model/Category.php',
    'Administrator\Model\Post'                          => __DIR__ . '/src/Administrator/Model/Post.php',
    'Administrator\Model\Profile'                       => __DIR__ . '/src/Administrator/Model/Profile.php',
    'Administrator\Model\User'                          => __DIR__ . '/src/Administrator/Model/User.php',
    'Administrator\Model\UserGroup'                     => __DIR__ . '/src/Administrator/Model/UserGroup.php',
    'Administrator\Model\Venue'                         => __DIR__ . '/src/Administrator/Model/Venue.php',
);
