<?php
$this->headMeta()->appendName('description', $this->translate('index_meta_description'));

$this->headLink()->appendStylesheet($this->basePath() . '/common/css/home.css');

$this->headScript()
    ->appendFile($this->basePath() . '/common/js/home.js')
    ->prependFile($this->basePath() . '/nivo-slider/js/jquery.nivo.slider.pack.js');
?>

<div id="overview" class="span12">
	<div id="about">
		<p>
            <?php echo $this->translate('blx_introdution')?>
        </p>
	</div>

	<div class="people-talk">
		<div class="block-header">
			<h2><?php echo $this->translate('Moi nguoi noi gi ve BLX.VN')?></h2>
		</div>
		<div class="block-body">
			<div id="people-talk-carousel" class="carousel slide"
				data-interval="1000">
				<?php
    // Random active item
//     $activeIndex = \Zend\Math\Rand::getInteger(0, 4);
    ?>
				<ol class="carousel-indicators">
					<li data-target="#people-talk-carousel" data-slide-to="0"
						class="active"></li>
					<li data-target="#people-talk-carousel" data-slide-to="1"></li>
					<li data-target="#people-talk-carousel" data-slide-to="2"></li>
					<li data-target="#people-talk-carousel" data-slide-to="3"></li>
					<li data-target="#people-talk-carousel" data-slide-to="4"></li>
				</ol>
				<!-- Carousel items -->
				<div class="carousel-inner">
					<div class="active item">
						<img class="avatar"
							src="<?php echo $this->basePath()?>common/images/avatar-tran-duc-duy-80x80.jpg"
							width="80" height="80"
							alt="<?php echo $this->translate('Tran Duc Duy sinh vien K55 Dai hoc Bach Khoa Ha Noi')?>"
							title="<?php echo $this->translate('Tran Duc Duy sinh vien K55 Dai hoc Bach Khoa Ha Noi')?>">

						<p class="quote">
                            <?php echo $this->translate('tran_duc_duy_talk_about_blx')?>
                        </p>

						<div class="clearfix"></div>
						<h6 class="people-info">
							<span class="people-name"><?php echo $this->translate('Tran Duc Duy')?></span>&nbsp;&dash;&nbsp;<span
								class="people-address"><?php echo $this->translate('sinh vien K55 Dai hoc Bach Khoa Ha Noi')?></span>
						</h6>
					</div>
					<div class="item">
						<img class="avatar"
							src="<?php echo $this->basePath()?>common/images/avatar-nguyen-manh-cuong-80x80.jpg"
							width="80" height="80"
							alt="<?php echo $this->translate('Nguyen Manh Cuong sinh vien K55 Dai hoc Bach Khoa Ha Noi')?>"
							title="<?php echo $this->translate('Nguyen Manh Cuong sinh vien K55 Dai hoc Bach Khoa Ha Noi')?>">

						<p class="quote">
                            <?php echo $this->translate('nguyen_manh_cuong_talk_about_blx')?>
                        </p>

						<div class="clearfix"></div>
						<h6 class="people-info">
							<span class="people-name"><?php echo $this->translate('Nguyen Manh Cuong')?></span>&nbsp;&dash;&nbsp;<span
								class="people-address"><?php echo $this->translate('sinh vien K55 Dai hoc Bach Khoa Ha Noi')?></span>
						</h6>
					</div>
					<div class="item">
						<img class="avatar"
							src="<?php echo $this->basePath()?>common/images/avatar-an-duy-khuong-80x80.jpg"
							width="80" height="80"
							alt="<?php echo $this->translate('An Duy Khuong sinh vien K55 Dai hoc Bach Khoa Ha Noi')?>"
							title="<?php echo $this->translate('An Duy Khuong sinh vien K55 Dai hoc Bach Khoa Ha Noi')?>">

						<p class="quote">
                            <?php echo $this->translate('an_duy_khuong_talk_about_blx')?>
                        </p>

						<div class="clearfix"></div>
						<h6 class="people-info">
							<span class="people-name"><?php echo $this->translate('An Duy Khuong')?></span>&nbsp;&dash;&nbsp;<span
								class="people-address"><?php echo $this->translate('sinh vien K56 Dai hoc Bach Khoa Ha Noi')?></span>
						</h6>
					</div>
					<div class="item">
						<img class="avatar"
							src="<?php echo $this->basePath()?>common/images/avatar-duong-hoai-thu-80x80.jpg"
							width="80" height="80"
							alt="<?php echo $this->translate('Duong Hoai Thu sinh vien Dai hoc khoa hoc Thai Nguyen')?>"
							title="<?php echo $this->translate('Duong Hoai Thu sinh vien Dai hoc khoa hoc Thai Nguyen')?>">

						<p class="quote">
                            <?php echo $this->translate('duong_hoai_thu_talk_about_blx')?>
                        </p>

						<div class="clearfix"></div>
						<h6 class="people-info">
							<span class="people-name"><?php echo $this->translate('Duong Hoai Thu')?></span>&nbsp;&dash;&nbsp;<span
								class="people-address"><?php echo $this->translate('sinh vien Dai hoc khoa hoc Thai Nguyen')?></span>
						</h6>
					</div>
					<div class="item">
						<img class="avatar"
							src="<?php echo $this->basePath()?>common/images/avatar-nguyen-van-tu-80x80.jpg"
							width="80" height="80"
							alt="<?php echo $this->translate('Nguyen Van Tu sinh vien Cao dang ky thuat Cong nghiep')?>"
							title="<?php echo $this->translate('Nguyen Van Tu sinh vien Cao dang ky thuat Cong nghiep')?>">

						<p class="quote">
                            <?php echo $this->translate('nguyen_van_tu_talk_about_blx')?>
                        </p>

						<div class="clearfix"></div>
						<h6 class="people-info">
							<span class="people-name"><?php echo $this->translate('Nguyen Van Tu')?></span>&nbsp;&dash;&nbsp;<span
								class="people-address"><?php echo $this->translate('sinh vien Cao dang ky thuat Cong nghiep')?></span>
						</h6>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="register-step" class="span12">
	<div class="block">
		<div class="block-header">
			<h2><?php echo $this->translate('Quy trinh thi cap bang lai xe hang A1')?></h2>
		</div>
		<div class="block-body">
			<ul>
				<li id="filing" class="step"><a href="#nop-ho-so">
						<h3><?php echo $this->translate('Nop ho so')?></h3> <span
						class="illustration base64"></span>
				</a></li>
				<li class="tri-angle-right"><i></i></li>
				<li id="view-fixture" class="step"><a
					href="<?php echo $this->url('fixture')?>">
						<h3><?php echo $this->translate('Xem lich thi')?></h3> <span
						class="illustration base64"></span>
				</a></li>
				<li class="tri-angle-right"><i></i></li>
				<li id="take-exam" class="step"><a
					href="<?php echo $this->url('guiding')?>">
						<h3><?php echo $this->translate('Di thi')?></h3> <span
						class="illustration base64"></span>
				</a></li>
				<li class="tri-angle-right"><i></i></li>
				<li id="view-result" class="step"><a
					href="<?php echo $this->url('result')?>">
						<h3><?php echo $this->translate('Xem ket qua')?></h3> <span
						class="illustration base64"></span>
				</a></li>
				<li class="tri-angle-right"><i></i></li>
				<li id="take-license" class="step"><a
					href="<?php echo $this->url('result')?>">
						<h3><?php echo $this->translate('Nhan bang')?></h3> <span
						class="illustration base64"></span>
				</a></li>
			</ul>
		</div>
	</div>
</div>

<div id="nop-ho-so" class="span12">
	<div class="block block-square">
		<div class="block-header block-header-inverse">
			<h2><?php echo $this->translate('Nop ho so truc tiep')?></h2>
		</div>
		<div class="block-body">
			<div class="profile-requirement">
				<div class="requirement">
					<h3><?php echo $this->translate('Ho so bao gom')?></h3>
					<ul>
						<li>
                            <?php echo $this->translate('3 anh chan dung 3x4')?>
                        </li>
						<li>
                            <?php echo $this->translate('1 ban photocopy chung minh thu 2 mat khong can cong chung')?>
                        </li>
					</ul>
				</div>

				<div class="note">
					<h3><?php echo $this->translate('Chu y le phi thi gom 2 khoan')?></h3>
					<ol>
						<li><?php echo $this->translate('Le phi dao tao 150.000<sup>d</sup>')?></li>
						<li><?php echo $this->translate('Le phi thi 225.000<sup>d</sup> (40.000<sup>d</sup> thi ly thuyet, 50.000<sup>d</sup> thi thuc hanh, 135.00<sup>d</sup> in va cap bang)')?></li>
					</ol>
				</div>
			</div>
			<div class="hotline">
			     <h3>
			     <?php echo $this->translate('Hotline nop ho so: Mr.Dung 0163 213 4476')?>
			     </h3>
			</div>
			<div class="filling-places">
			    <div class="map-container">
					<div id="map-canvas"></div>
				</div>
				<div class="places">
				    <h3><?php echo $this->translate('Dia diem nop ho so')?></h3>
				    <div id="findNearestLocation"><?php echo $this->translate('Tim dia diem gan nhat <sup><i>(thu nghiem)</i></sup>')?></div>
				    <table class="table table-hover table-bordered">
				        <thead>
				            <tr>
				                <th><?php echo $this->translate('Cong tac vien')?></th>
				                <th><?php echo $this->translate('Dia chi')?></th>
				                <th><?php echo $this->translate('Quan')?></th>
				            </tr>
				        </thead>
				        <tbody>
				            <tr data-longitude="21.005321" data-latitude="105.847150" data-title="<?php echo $this->translate('Do Viet Dung')?>" data-info="<?php echo $this->translate('Cong tac vien Do Viet Dung')?>">
				                <td><?php echo $this->translate('Do Viet Dung')?></td>
				                <td><?php echo $this->translate('Phong 507 KTX B10 DH Bach Khoa HN')?></td>
				                <td><?php echo $this->translate('Hai Ba Trung')?></td>
				            </tr>
				            <tr data-longitude="21.006347" data-latitude="105.846906" data-title="<?php echo $this->translate('Khuong Manh Duy')?>" data-info="<?php echo $this->translate('Cong tac vien Khuong Manh Duy')?>">
				                <td><?php echo $this->translate('Khuong Manh Duy')?></td>
				                <td><?php echo $this->translate('Phong 105 KTX B5 DH Bach Khoa HN')?></td>
				                <td><?php echo $this->translate('Hai Ba Trung')?></td>
				            </tr>
				            <tr data-longitude="21.004975" data-latitude="105.847043" data-title="<?php echo $this->translate('Luong Cam Khang')?>" data-info="<?php echo $this->translate('Cong tac vien Luong Cam Khang')?>">
				                <td><?php echo $this->translate('Luong Cam Khang')?></td>
				                <td><?php echo $this->translate('Phong 101 KTX B10 DH Bach Khoa HN')?></td>
				                <td><?php echo $this->translate('Hai Ba Trung')?></td>
				            </tr>
				            <tr data-longitude="21.010654" data-latitude="105.824999" data-title="<?php echo $this->translate('Phan Thi Yen')?>" data-info="<?php echo $this->translate('Cong tac vien Phan Thi Yen')?>">
				                <td><?php echo $this->translate('Phan Thi Yen')?></td>
				                <td><?php echo $this->translate('178 Tay Son (Doi dien truong DH Cong Doan)')?></td>
				                <td><?php echo $this->translate('Dong Da')?></td>
				            </tr>
				            <tr data-longitude="21.00197" data-latitude="105.846488" data-title="<?php echo $this->translate('Le Cong Hoan')?>" data-info="<?php echo $this->translate('Cong tac vien Le Cong Hoan')?>">
				                <td><?php echo $this->translate('Le Cong Hoan')?></td>
				                <td><?php echo $this->translate('121 Le Thanh Nghi (Doi dien truong Xay Dung)')?></td>
				                <td><?php echo $this->translate('Hai Ba Trung')?></td>
				            </tr>
				            <tr data-longitude="21.043777" data-latitude="105.780846" data-title="<?php echo $this->translate('Pham Phuong Thao')?>" data-info="<?php echo $this->translate('Cong tac vien Pham Phuong Thao')?>">
				                <td><?php echo $this->translate('Pham Phuong Thao')?></td>
				                <td><?php echo $this->translate('118 Pham Van Dong (Doi dien DH Ngoai Ngu)')?></td>
				                <td><?php echo $this->translate('Cau Giay')?></td>
				            </tr>
				            <tr data-longitude="20.956791" data-latitude="105.808784" data-title="<?php echo $this->translate('Nguyen Van Tu')?>" data-info="<?php echo $this->translate('Cong tac vien Nguyen Van Tu')?>">
				                <td><?php echo $this->translate('Nguyen Van Tu')?></td>
				                <td><?php echo $this->translate('Canh truong cao dang kinh te cong nghiep HN')?></td>
				                <td><?php echo $this->translate('Thanh Xuan')?></td>
				            </tr>
				        </tbody>
				    </table>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="blx-social-network" class="span12">
	<div class="block">
		<div class="block-body">
			<div class="blx-on-social-network">
				<h2><?php echo $this->translate('BLX.VN tren mang xa hoi')?></h2>
			</div>
			<ul class="social-network-list">
				<li><a href="https://www.facebook.com/blxvn"> <img
						src="common/images/facebook-logo-38x38.png" width="38" height="38"
						alt="" title="">
				</a></li>
				<li><a href="https://www.youtube.com/channel/UCPxfXvNhC0VtfxEIEHkIzmA"> <img src="common/images/youtube-logo-38x38.png"
						width="38" height="38" alt="" title="">
				</a></li>
				<li><a href="https://twitter.com/blxvn"> <img src="common/images/twitter-logo-38x38.png"
						width="38" height="38" alt="" title="">
				</a></li>
				<li><a href="https://plus.google.com/110647196881609058917/posts"> <img src="common/images/google-plus-logo-38x38.png"
						width="38" height="38" alt="" title="">
				</a></li>
			</ul>
		</div>
	</div>
</div>